#! /usr/bin/env python3
import requests
import sys

flickr_key = '34662e4ac90a3a220420477bd10e4b5a'
flickr_secret = 'ba131d9d759628ad'

tags = str(sys.argv[1])

params = {
    'api_key': flickr_key,
    'tags': tags,
    'tag_mode': 'all',
    'method': 'flickr.photos.search',
    'per_page': 10,
    'media': 'photos',
    'format': 'json',
    'nojsoncallback': 1
}


def get_data(flickr_data):
    photos_data_list = []
    for photo_dict in flickr_data['photos']['photo']:
        photos_data_list.append([photo_dict['id'], photo_dict['owner']])

    return photos_data_list


page = requests.get("https://api.flickr.com/services/rest/", params=params)
api_res = page.json()
# print(api_res)
photos_list = get_data(api_res)
for owner_id in photos_list:
    url = 'https://www.flickr.com/photos/{}/{}'.format(owner_id[1], owner_id[0])
    print(url)
