#! /usr/bin/env python3
import requests
import json
import sys

term = ' '.join(sys.argv[2:])
if sys.argv[1] == '-p':
    media = 'podcast'
elif sys.argv[1] == '-m':
    media = 'music'
elif sys.argv[1] == '-M':
    media = 'movie'
else:
    print('Usage: [-pmM][--name]')
    print('m for music, p for podcast and M for Movie')
    exit()

params = {
    'term': term,
    'country': 'us',
    'media': media
}


def get_data(attachment):
    podcasts = []
    for track_nb in range(attachment['resultCount']):
        podcasts.append(attachment['results'][track_nb]['trackName'])

    return podcasts


page = requests.get("https://itunes.apple.com/search", params=params)
api_res = page.json()
# print(api_res)
data = get_data(api_res)
for podcast in data:
    print(podcast)
